# Generated by Django 5.0.7 on 2026-01-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_room', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за одну комнату')),
                ('price_per_bathroom', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена за один туалет')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки цен',
                'verbose_name_plural': 'Настройки цен',
            },
        ),
    ]
