# Generated by Django 5.0.7 on 2026-01-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип уборки')),
                ('base_price_per_m2', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базовая цена за м²')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Коэффициент сложности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип уборки',
                'verbose_name_plural': 'Типы уборки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DryCleaningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект химчистки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('unit', models.CharField(choices=[('item', 'За единицу'), ('m2', 'За м²')], default='item', max_length=10, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Химчистка',
                'verbose_name_plural': 'Химчистка',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Дополнительная услуга')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('per_m2', 'Цена за м²')], default='fixed', max_length=10, verbose_name='Тип цены')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'ordering': ['name'],
            },
        ),
    ]
