# Generated by Django 5.0.7 on 2026-01-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_cleaningtype_drycleaningservice_extraservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Basic'), ('general', 'General'), ('general_plus', 'General Plus')], max_length=20, verbose_name='Уровень уборки')),
                ('title', models.CharField(help_text='Например: До 50 m², 50–80 m², +10 m²', max_length=50, verbose_name='Название диапазона')),
                ('area_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь от (м²)')),
                ('area_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь до (м²)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена (для акции)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Цена уборки',
                'verbose_name_plural': 'Цены уборки',
                'ordering': ['level', 'sort_order', 'area_from'],
            },
        ),
        migrations.CreateModel(
            name='PromoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('text', models.CharField(default='20% do 15.01', help_text='Например: 20% do 15.01, AKCE, SLEVA, -350 Kč', max_length=100, verbose_name='Текст акции')),
            ],
            options={
                'verbose_name': 'Текст акции',
                'verbose_name_plural': 'Тексты акций',
            },
        ),
    ]
