# Generated by Django 5.0.7 on 2026-01-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_cleaningprice_promotext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('cleaning_level', models.CharField(choices=[('basic', 'Basic'), ('general', 'General'), ('general_plus', 'General Plus')], max_length=20, verbose_name='Уровень уборки')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Площадь (м²)')),
                ('rooms', models.PositiveIntegerField(default=0, verbose_name='Количество комнат')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Количество туалетов')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('desired_time', models.TimeField(blank=True, null=True, verbose_name='Желаемое время')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
