# Generated by Django 5.0.7 on 2026-01-07 14:38

import django.core.validators
from django.db import migrations, models


def update_orders_area(apps, schema_editor):
    """Обновляем записи с area=0 перед миграцией"""
    Order = apps.get_model('calculator', 'Order')
    # Обновляем все записи с area=0 на area=10 (минимальное значение)
    Order.objects.filter(area=0).update(area=10)


def reverse_update_orders_area(apps, schema_editor):
    """Обратная операция не требуется"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_advantage_companyinfo_galleryitem_review'),
    ]

    operations = [
        # Сначала обновляем существующие записи
        migrations.RunPython(update_orders_area, reverse_update_orders_area),
        migrations.CreateModel(
            name='DateDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='0 = нет скидки, 10 = -10%, 20 = -20% и т.д.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Скидка по дате',
                'verbose_name_plural': 'Скидки по датам',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='applied_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Скидка, применённая при выборе даты', verbose_name='Применённая скидка (%)'),
        ),
    ]
