# Generated by Django 5.0.7 on 2026-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_datediscount_order_applied_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datediscount',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='datediscount',
            unique_together={('date', 'discount_percent')},
        ),
    ]
