# Generated by Django 5.0.7 on 2026-01-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_datediscount_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtype',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение, которое будет отображаться на сайте', null=True, upload_to='cleaning_types/', verbose_name='Фото типа уборки'),
        ),
        migrations.AddField(
            model_name='drycleaningservice',
            name='image',
            field=models.ImageField(blank=True, help_text='Фото будет показано в блоке услуг', null=True, upload_to='dry_cleaning/', verbose_name='Фото услуги'),
        ),
    ]
