# Generated by Django 5.0.7 on 2026-01-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_cleaningtype_image_drycleaningservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='description_cs',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='cleaningprice',
            name='title_cs',
            field=models.CharField(help_text='Например: До 50 m², 50–80 m², +10 m²', max_length=50, null=True, verbose_name='Название диапазона'),
        ),
        migrations.AddField(
            model_name='cleaningprice',
            name='title_en',
            field=models.CharField(help_text='Например: До 50 m², 50–80 m², +10 m²', max_length=50, null=True, verbose_name='Название диапазона'),
        ),
        migrations.AddField(
            model_name='cleaningprice',
            name='title_ru',
            field=models.CharField(help_text='Например: До 50 m², 50–80 m², +10 m²', max_length=50, null=True, verbose_name='Название диапазона'),
        ),
        migrations.AddField(
            model_name='cleaningtype',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип уборки'),
        ),
        migrations.AddField(
            model_name='cleaningtype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип уборки'),
        ),
        migrations.AddField(
            model_name='cleaningtype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип уборки'),
        ),
        migrations.AddField(
            model_name='drycleaningservice',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Объект химчистки'),
        ),
        migrations.AddField(
            model_name='drycleaningservice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Объект химчистки'),
        ),
        migrations.AddField(
            model_name='drycleaningservice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Объект химчистки'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, verbose_name='Дополнительная услуга'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Дополнительная услуга'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Дополнительная услуга'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption_cs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подпись'),
        ),
        migrations.AddField(
            model_name='promotext',
            name='text_cs',
            field=models.CharField(default='20% do 15.01', help_text='Например: 20% do 15.01, AKCE, SLEVA, -350 Kč', max_length=100, null=True, verbose_name='Текст акции'),
        ),
        migrations.AddField(
            model_name='promotext',
            name='text_en',
            field=models.CharField(default='20% do 15.01', help_text='Например: 20% do 15.01, AKCE, SLEVA, -350 Kč', max_length=100, null=True, verbose_name='Текст акции'),
        ),
        migrations.AddField(
            model_name='promotext',
            name='text_ru',
            field=models.CharField(default='20% do 15.01', help_text='Например: 20% do 15.01, AKCE, SLEVA, -350 Kč', max_length=100, null=True, verbose_name='Текст акции'),
        ),
    ]
