# Generated by Django 5.0.7 on 2026-01-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_advantage_description_cs_advantage_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dry_cleaning_items',
            field=models.TextField(blank=True, help_text='Выбранные позиции химчистки с количеством', null=True, verbose_name='Объекты химчистки'),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_services',
            field=models.TextField(blank=True, help_text='Перечень выбранных дополнительных услуг', null=True, verbose_name='Дополнительные услуги'),
        ),
    ]
