# Generated by Django 4.2.7 on 2026-04-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_order_dry_cleaning_items_order_extra_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опции')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название опции')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название опции')),
                ('name_cs', models.CharField(max_length=200, null=True, verbose_name='Название опции')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фиксированная цена (крон)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Доп. опция грузоперевозки',
                'verbose_name_plural': 'Грузоперевозки — Доп. опции',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CargoTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тарифа')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название тарифа')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название тарифа')),
                ('name_cs', models.CharField(max_length=200, null=True, verbose_name='Название тарифа')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час (крон)')),
                ('min_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='Минимальное количество часов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тариф грузоперевозки',
                'verbose_name_plural': 'Грузоперевозки — Тарифы',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('cleaning', 'Уборка помещений'), ('drycleaning', 'Химчистка мебели'), ('cargo', 'Грузоперевозки'), ('shoe_cleaning', 'Химчистка обуви')], max_length=50, unique=True, verbose_name='Тип услуги')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок карточки')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок карточки')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок карточки')),
                ('title_cs', models.CharField(max_length=200, null=True, verbose_name='Заголовок карточки')),
                ('description', models.CharField(max_length=500, verbose_name='Описание карточки')),
                ('description_ru', models.CharField(max_length=500, null=True, verbose_name='Описание карточки')),
                ('description_en', models.CharField(max_length=500, null=True, verbose_name='Описание карточки')),
                ('description_cs', models.CharField(max_length=500, null=True, verbose_name='Описание карточки')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 600×400 px', null=True, upload_to='service_categories/', verbose_name='Фото карточки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуг (карточки)',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ShoeCleaningService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип обуви')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Тип обуви')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Тип обуви')),
                ('name_cs', models.CharField(max_length=200, null=True, verbose_name='Тип обуви')),
                ('price_per_pair', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за пару (крон)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Химчистка обуви',
                'verbose_name_plural': 'Химчистка обуви',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
