# Generated by Django 4.2.7 on 2026-03-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_order_dry_cleaning_items_order_extra_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='google_sheets_url',
            field=models.URLField(blank=True, help_text='URL таблицы Google Sheets для просмотра заявок', null=True, verbose_name='Ссылка на Google Таблицу'),
        ),
    ]
